#archivo de configuracion para docker-compose en desarrollo
#docker-compose up -d

version: '3'
services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pokedex
    volumes:
      - ./mongo:/data/db
